apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deploy
  labels:
    app: testing-redis-deploy
spec:
  selector:
    matchLabels:
      app: testing-redis-pod
  template:
    metadata:
      name: redis-app
      labels:
        app: testing-redis-pod
    spec:
      containers:
        - name: redis
          image: redis
  replicas: 2

---

apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: testing-redis-svc
spec:
  selector:
    app: testing-redis-pod
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
