apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-deploy
  labels:
    app: testing-voting-deploy
spec:
  selector:
    matchLabels:
      app: testing-voting-deploy
  template:
    metadata:
      name: voting-app
      labels:
        app: testing-voting-deploy
    spec:
      containers:
        - name: voting-app
          image: kodekloud/examplevotingapp_vote:v1
  replicas: 2

---

apiVersion: v1
kind: Service
metadata:
  name: voting-svc
  labels:
    app: testing-voting-svc
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30010
  selector:
    app: testing-voting-deploy
